name: Update SST OI data
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5


      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy scipy matplotlib xarray dask netCDF4 bottleneck       
    
      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: Download file from Google Drive, encoded service secret
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./TS_monthly.nc
          googleFileId: 1_Zfxn0dcIQ8M4A_50Sj3bB8pGWvBD678

      - name: Print dir tree and check disk space
        shell: bash -l {0}
        run: |
          tree
          df -h
          which python

      - name: Test conda installation
        shell: bash -l {0}
        run: conda info


      - name: update sst oi monthly
        shell: bash -l {0}
        run: python code_gha/SSTspatial/sst_oi_daily_v21_update.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h

      - name: sst daily and monthly update upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: data_sstspatial_gha
