name: Code1  DO NH IEA Time Series
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV
      - name: Download NH05 aragonite netcdf file
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./NH05_AragSat.nc
          googleFileId: 
      - name: Download NH25 aragonite netcdf file
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./NH25_AragSat.nc
          googleFileId: 

      - name: Create IEA R style CSV files Monthly
        run: python code_gha/OceanAcidification/create_oc_arag_nh_M_std.py
      - name: Create IEA R style CSV files Seasonal
        run: python code_gha/OceanAcidification/create_oc_arag_nh_S_std.py
      - name: Plot IEA style seasonal figures
        run: python code_gha/OceanAcidification/plot_do_IEA_figs_nh_MS_threshold.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h
      - name: git auto commit -- save calcofi station netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
