name: Code1 calcoficsv
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy pandas scipy matplotlib xarray dask netCDF4 bottleneck requests cartopy seawater


      - name: Download CalCOFI Bottle and Prelim CTD zip file
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./csv_database_gha.zip
          googleFileId: 1sA3FaILktBH8csSjdelnl239K2gg_KvA
      - name: Unzip file
        run: unzip ./csv_database_gha.zip
      - name: create prelim CTD netcdf
        shell: bash -l {0}
        run: python code_gha/calcoficsv/prelim_ctd2netcdf.py
      - name: Loop over all CalCOFI stations and create station netcd files
        shell: bash -l {0}
        run: python code_gha/calcoficsv/bottle_append_prelim_ctd_2netcdf_stations.py
      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h
      - name: git auto commit -- save calcofi station netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
