name: Contour SST spatial status/trends 
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy pandas scipy matplotlib xarray dask netCDF4 bottleneck requests cartopy seawater

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV
      - name: Download file from Google Drive, encoded service secret
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./TS_monthly.nc
          googleFileId: 1n7uOfzEfrv9Cg6YVxl20Sp3vqvLjrVGb

      - name: create sst spatial iea stautus/trends
        shell: bash -l {0}
        run: python code_gha/SSTspatial/create_oc_sst_S_spatial.py

      - name: contour sst spatial iea status/trends
        shell: bash -l {0}
        run: python code_gha/SSTspatial/contour_oc_sst_S_spatial.py

      - name: git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
