name: Code1 DO Spatial CalCOFI
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV
      - name: Download NH25 CTD netcdf file
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./NH25_CTD.nc
          googleFileId: 1Y7dEbbIClChXu3UR0OUANmQRNqrcodt3
      - name: Combine all DO data at all statoins at selected depths, also min/max values.
        run: python code_gha/DissolvedOxygen/calcofi_do_at_depths_min_values_between_z1_z2.py
      - name: Get the IEA stats from the DO station/depth data.
        run: python code_gha/DissolvedOxygen/DissolvedOxygen/calcofi_do_get_IEA_data_symbols.py
      - name: Figues of spatial DO CalCOFI
        run: python code_gha/DissolvedOxygen/contour_oc_do_S_spatial.py
      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h
      - name: git auto commit -- save calcofi station netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
