name: Code1 DO -- CalCOFI IEA CSV files
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge,defaults
          python-version: 3.12
          # These properties enable the use of mamba, which is much faster and far less error
          # prone than conda while being completely compatible with the conda CLI
          use-mamba: true
          mamba-version: "*"	  

      - name: Install some packages
        # The `-l` is needed so conda environment activation works correctly
        shell: bash -l {0}
        run: |
          mamba install -c conda-forge numpy pandas scipy matplotlib xarray dask netCDF4 bottleneck requests cartopy seawater

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: At select station get DO at certain depths
        shell: bash -l {0}      
        run: python code_gha/DissolvedOxygen/calcofi_do_ts_at_depths_select_stations.py
      - name: Create IEA R style CSV files Monthly
        shell: bash -l {0}      
        run: python code_gha/DissolvedOxygen/create_oc_do_calcofi_M_std.py
      - name: Create IEA R style CSV files Seasonal
        shell: bash -l {0}      
        run: python code_gha/DissolvedOxygen/create_oc_do_calcofi_S_std.py
      - name: Plot IEA time series
        shell: bash -l {0}      
        run: python code_gha/DissolvedOxygen/plot_do_IEA_figs_calcofi_S.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h
      - name: git auto commit -- save calcofi station netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
