name: Code1 NPH, pmsl update

env:
  PYTHON_VERSION: "3.12"


on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
            echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: install Octave
        run: |
          sudo apt-get -y install octave octave-netcdf octave-image
      - name: Run Python download data from Erddap
        run: python code_gha/NPH/pmsl_monthly_update.py
      - name: Run Octave calc NPH and save to CSV
        run: octave code_gha/NPH/calc_nph.m

      - name: sst daily and monthly update upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: data_x13

      - name: Remove download diretory an list 
        shell: bash {0}
        run: |
          rm -r data_x13
          tree
          df -h

      - name: git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
