name: Python Download Bakun UI

env:
  PYTHON_VERSION: "3.12"


on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: code3_bakunUI_gha, Run Python download data from Erddap
        run: python code_gha/bakunUI/download_bakunUI_gha.py

      - name: code4_bakunUI_gha, Run Python create daily, monthly from 6 hr
        run: python code_gha/bakunUI/download_bakunUI_gha.py

      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h

      - name: code5_bakunUI_gha, Run Python save data to R style CSV Monthly
        run: python code_gha/bakunUI/create_oc_bakunUI_M_std.py

      - name: code6_bakunUI_gha, Run Python save data to R style CSV Seasonal
        run: python code_gha/bakunUI/create_oc_bakunUI_S_std.py

      - name: code7_bakunUI_gha, Run Python plot R style CSV both Monthly and Seasonal
        run: python code_gha/bakunUI/plot_IEA_figs_MS.py

      - name: git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
