name: Code1 NPH, create and plot IEA CSV files

env:
  PYTHON_VERSION: "3.12"


on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
            echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV

      - name: code3_nphIEA_gha, save jan-feb and monthly NPH area netcdf
        run: python code_gha/NPH/calc_jan_feb_area_nph.py

      - name: code4_nphIEA_gha, IEA CSV for jan-feb NPH
        run: python code_gha/NPH/create_oc_janfeb_nph_A_std.py
      - name: code5_nphIEA_gha, IEA CSV for monthly NPH
        run: python code_gha/NPH/create_oc_nph_M_std.py
      - name: code6_nphIEA_gha, IEA CSV for seasonal NPH
        run: python code_gha/NPH/create_oc_nph_S_std.py

      - name: code7_nphIEA_gha, plot month and seasonal
        run: python code_gha/NPH/plot_iea_figs_MS.py
      - name: code8_nphIEA_gha, plot jan-feb 
        run: python code_gha/NPH/plot_iea_figs_A.py
      - name: code9_nphIEA_gha, plot all months
        run: python code_gha/NPH/plot_iea_indiviual_months_A.py

      - name: git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
      - name: sst daily and monthly update upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: data_x13
