name: Code1 calcoficsv
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: '**/code1_basin_gha_requirements'

      - run: python -m pip install -r .github/workflows/code1_basin_gha_requirements

      - name: set pythonpath
        run: |
          echo "PYTHONPATH=code_gha/fun_gha/" >> $GITHUB_ENV
      - name: Download CalCOFI Bottle and Prelim CTD zip file
        uses: Fork-on-the-Table-Collective/upload-to-download-from-gdrive@v2.0.0
        with:
          credentials: ${{ secrets.SERVICE_ACCOUNT_KEY_JSON }}
          actionType: download
          localPath: ./csv_database_gha.zip
          googleFileId: 1sA3FaILktBH8csSjdelnl239K2gg_KvA
      - name: Unzip file
        run: unzip ./csv_database_gha.zip
      - name: create prelim CTD netcdf
        run: python code_gha/calcoficsv/prelim_ctd2netcdf.py
      - name: Loop over all CalCOFI stations and create station netcd files
        run: python code_gha/calcoficsv/bottle_append_prelim_ctd_2netcdf_stations.py
      - name: Print dir tree and check disk space
        shell: bash {0}
        run: |
          tree
          df -h
      - name: git auto commit -- save calcofi station netcdf
        uses: stefanzweifel/git-auto-commit-action@v7
